### ISSUE TITLE
厉害了小哥，怎么绕过验证码的

### ISSUE THREAD

**Issue by cyy53589** [wumcpq/scnu_ssp_ClockIn#1]
我也写了自动打卡，但是因为不能绕过验证码，我就曲线救国模拟浏览器微博登录了。
你是怎么绕过验证码的？

**Comment by cyy53589** [comment]
本地登录……我倒是没有想到还有这岔

**Comment by Q-Bug4** [comment]
哈哈哈哈哈哈哈直接在ssp那边登录就可以了，ssp那里不用验证码。
