### ISSUE TITLE
同道中人

### ISSUE THREAD

**Issue by Cosinhs** [wumcpq/scnu_ssp_ClockIn#3]
https://github.com/Cosinhs/scnu_daily_jkdk/blob/master/jkdk.py
那个后台网站有点新的小改动，代码实现更简单了。另外服务端还是没有校检填写温度的地方，可以任意填写（50字节以内的）文本内容。

**Comment by wumcpq** [comment]
牛的啊，学习了

**Comment by Q-Bug4** [comment]
> https://github.com/Cosinhs/scnu_daily_jkdk/blob/master/jkdk.py
> 那个后台网站有点新的小改动，代码实现更简单了。另外服务端还是没有校检填写温度的地方，可以任意填写（50字节以内的）文本内容。

强，学习了
